# -*- coding: utf-8 -*-
"""copyAndImageTopdf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DBhan0g9xNHURyzprWqGAZQCjLiSzA_
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  Google Colab Script — PDF → Image → Drive + Sheet3             ║
# ║  Columns: A=date  B=title  C=category  D=link  E=PDF  F=status  ║
# ║                                                                  ║
# ║  FLOW:                                                           ║
# ║  1. Find rows in Sheet1 where F = "Pending"                     ║
# ║  2. Download PDF from col E, convert to PNG (named from col B)  ║
# ║  3. Upload PNG to Drive folder                                   ║
# ║  4. Copy row + image link → Sheet3                              ║
# ║  5. Update Sheet1 col F: "Pending" → "Done"                     ║
# ║  6. Duplicate-safe: skips rows already "Done" in Sheet1         ║
# ╚══════════════════════════════════════════════════════════════════╝

# ── Authenticate first ────────────────────────────────────────────
from google.colab import auth
auth.authenticate_user()

# ── Install dependencies ──────────────────────────────────────────
import subprocess
subprocess.run(["pip", "install", "pdf2image", "Pillow", "gspread", "--quiet"], check=True)
subprocess.run(["apt-get", "install", "-y", "-q", "poppler-utils"], check=True)

# ── Imports ───────────────────────────────────────────────────────
import io
import re
import gspread
from google.auth import default
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseUpload, MediaIoBaseDownload
from pdf2image import convert_from_bytes

# ── CONFIG ────────────────────────────────────────────────────────
SPREADSHEET_ID  = "1bRKltdzjaafftARgbVoZfLV_yFxhhAgS3Y-mHsgtAbw"
SOURCE_SHEET    = "Sheet1"
DEST_SHEET      = "Sheet3"

# 0-indexed column positions
STATUS_COL_IDX  = 5   # F — status
PDF_COL_IDX     = 4   # E — driveWebviewlink (PDF)
TITLE_COL_IDX   = 1   # B — title

# Google Drive folder to upload images into
DRIVE_FOLDER_ID = "1CxB8P7hHi_OGvX0c7xGKyRsMOUe7-qfH"

# Status labels (case-insensitive matching)
STATUS_PENDING  = "pending"
STATUS_DONE     = "Done"   # written back to Sheet1 exactly as this

# ── Auth clients ──────────────────────────────────────────────────
creds, _  = default()
gc        = gspread.authorize(creds)
drive_svc = build("drive", "v3", credentials=creds)

# ══════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════

def slugify(text: str, max_len: int = 80) -> str:
    """Turn a title into a safe filename slug."""
    text = text.strip().lower()
    text = re.sub(r"[^\w\s-]", "",  text)   # remove special chars
    text = re.sub(r"[\s_-]+",  "_", text)   # spaces → underscores
    text = re.sub(r"^[-_]+|[-_]+$", "", text)
    return text[:max_len] or "untitled"


def extract_drive_file_id(url: str):
    """Extract file ID from any Google Drive URL."""
    for pat in [r"/file/d/([a-zA-Z0-9_-]+)", r"[?&]id=([a-zA-Z0-9_-]+)"]:
        m = re.search(pat, url)
        if m:
            return m.group(1)
    return None


def download_pdf_bytes(url: str) -> bytes:
    """Download a PDF via Google Drive API."""
    file_id = extract_drive_file_id(url)
    if not file_id:
        raise ValueError(f"Cannot extract Drive file ID from: {url}")
    buf = io.BytesIO()
    dl  = MediaIoBaseDownload(buf, drive_svc.files().get_media(fileId=file_id))
    done = False
    while not done:
        _, done = dl.next_chunk()
    return buf.getvalue()


def pdf_to_png_bytes(pdf_bytes: bytes, dpi: int = 150) -> bytes:
    """Convert first page of PDF → PNG bytes."""
    pages = convert_from_bytes(pdf_bytes, dpi=dpi, first_page=1, last_page=1)
    if not pages:
        raise ValueError("PDF returned no pages.")
    buf = io.BytesIO()
    pages[0].save(buf, format="PNG")
    return buf.getvalue()


def upload_to_drive(png_bytes: bytes, filename: str, folder_id: str) -> str:
    """Upload PNG to Drive, make public, return shareable link."""
    meta  = {"name": filename, "parents": [folder_id]}
    media = MediaIoBaseUpload(io.BytesIO(png_bytes), mimetype="image/png", resumable=False)
    f     = drive_svc.files().create(body=meta, media_body=media, fields="id").execute()
    fid   = f["id"]
    drive_svc.permissions().create(
        fileId=fid,
        body={"type": "anyone", "role": "reader"}
    ).execute()
    return f"https://drive.google.com/uc?id={fid}"


def get_or_create_sheet(spreadsheet, name: str, num_cols: int):
    """Return existing worksheet or create a new one."""
    try:
        return spreadsheet.worksheet(name)
    except gspread.exceptions.WorksheetNotFound:
        ws = spreadsheet.add_worksheet(title=name, rows=1000, cols=num_cols + 1)
        print(f"  ✦ Created new worksheet: '{name}'")
        return ws

# ══════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════

def main():
    print("=" * 62)
    print("   Pending → Process → Done  |  PDF → Image → Drive → Sheet3")
    print("=" * 62)

    spreadsheet = gc.open_by_key(SPREADSHEET_ID)
    src_ws      = spreadsheet.worksheet(SOURCE_SHEET)
    all_rows    = src_ws.get_all_values()

    if not all_rows or len(all_rows) < 2:
        print("Sheet1 is empty or has no data rows.")
        return

    header    = all_rows[0]
    data_rows = all_rows[1:]   # row index offset: data_rows[i] → Sheet row i+2

    # ── Prepare Sheet3 ────────────────────────────────────────────
    dest_ws   = get_or_create_sheet(spreadsheet, DEST_SHEET, len(header))
    dest_data = dest_ws.get_all_values()

    if not dest_data:
        dest_ws.append_row(header + ["Image Link"])
        dest_data = [header + ["Image Link"]]

    # Build duplicate-check set from Sheet3 col B (title), lowercased
    processed_titles = {
        row[TITLE_COL_IDX].strip().lower()
        for row in dest_data[1:]
        if len(row) > TITLE_COL_IDX and row[TITLE_COL_IDX].strip()
    }
    print(f"\n  Already in Sheet3   : {len(processed_titles)} row(s)")

    # ── Scan Sheet1 for Pending rows ──────────────────────────────
    pending_rows = []
    for i, row in enumerate(data_rows):
        padded = row + [""] * (max(STATUS_COL_IDX, PDF_COL_IDX, TITLE_COL_IDX) + 1 - len(row))
        if padded[STATUS_COL_IDX].strip().lower() == STATUS_PENDING:
            pending_rows.append((i, padded))

    print(f"  Pending in Sheet1   : {len(pending_rows)} row(s)\n")

    if not pending_rows:
        print("  ✅ Nothing to process — no Pending rows found in Sheet1.")
        return

    done_count  = 0
    skip_count  = 0
    error_count = 0

    for i, row in pending_rows:
        sheet1_row_num = i + 2        # 1-indexed sheet row (header is row 1)
        title     = row[TITLE_COL_IDX].strip()
        title_key = title.lower()
        pdf_url   = row[PDF_COL_IDX].strip()

        print(f"  [ROW {sheet1_row_num}] '{title[:55]}'")

        # ── Duplicate guard ───────────────────────────────────────
        if title_key in processed_titles:
            print(f"    ⏭  Already in Sheet3 — skipping & marking Done.\n")
            # Still mark Done in Sheet1 so it doesn't reappear as Pending
            src_ws.update_cell(sheet1_row_num, STATUS_COL_IDX + 1, STATUS_DONE)
            skip_count += 1
            continue

        image_link = ""
        success    = True

        if pdf_url:
            try:
                print(f"    → Downloading PDF…")
                pdf_bytes = download_pdf_bytes(pdf_url)

                print(f"    → Converting to image…")
                png_bytes = pdf_to_png_bytes(pdf_bytes)

                filename  = slugify(title) + ".png"
                print(f"    → Uploading '{filename}' to Drive…")
                image_link = upload_to_drive(png_bytes, filename, DRIVE_FOLDER_ID)
                print(f"    ✓ Image: {image_link}")

            except Exception as e:
                print(f"    ✗ ERROR: {e}")
                image_link = f"ERROR: {e}"
                success    = False
                error_count += 1
        else:
            print(f"    ⚠  No PDF URL in col E — row copied without image.")

        # ── Copy row to Sheet3 ────────────────────────────────────
        dest_ws.append_row(list(row) + [image_link], value_input_option="USER_ENTERED")
        processed_titles.add(title_key)

        # ── Update Sheet1 status: Pending → Done ─────────────────
        # Always mark Done (even on PDF error) so the row isn't
        # retried endlessly. The error message is saved in Sheet3.
        src_ws.update_cell(sheet1_row_num, STATUS_COL_IDX + 1, STATUS_DONE)
        print(f"    ✓ Sheet1 row {sheet1_row_num} status updated → '{STATUS_DONE}'\n")

        done_count += 1

    # ── Summary ───────────────────────────────────────────────────
    print("=" * 62)
    print(f"  ✅ Processed & marked Done : {done_count}")
    print(f"  ⏭  Skipped (already done)  : {skip_count}")
    print(f"  ❌ Errors (see Sheet3)      : {error_count}")
    print("=" * 62)


main()